### ISSUE TITLE
Add support for Last-Modified.

### ISSUE THREAD

**Issue by csarven** [linkeddata/gold#64]
If a resource is readable, the `Last-Modified` header should be returned.

**Comment by deiu** [comment]
`Last-Modified` was never implemented in gold. We've only used ETag so far and there were no plans to implement Last-Modified yet.

**Comment by akuckartz** [comment]
RFC 7232 states:
> An origin server SHOULD send Last-Modified for any selected
   representation for which a last modification date can be reasonably
   and consistently determined, since its use in conditional requests
   and evaluating cache freshness ([RFC7234]) results in a substantial
   reduction of HTTP traffic on the Internet and can be a significant
   factor in improving service scalability and reliability.
https://tools.ietf.org/html/rfc7232#section-2.2.1

**Comment by deiu** [comment]
Sure, but that's just `one` method of determining cache freshness. We're currently using `ETag` for that.

**Comment by csarven** [comment]
My initial comment didn't specify as to how this header can be used by consumers. `Last-Modified` provides a human and machine-readable value, and it is certainly not solely about caches.

My point here is that, please consider this as a feature request which is really not something far fetched, if anything, quite useful!

**Comment by deiu** [comment]
It should be titled and framed as a request instead of a question. I will update the title and reopen it for now.

**Comment by dmitrizagidulin** [comment]
Moving to https://github.com/solid/solid/issues/10 as a result of the [solid project workflow discussion](https://github.com/solid/solid-spec/issues/75). Closing.
