### ISSUE TITLE
Proxy injecting 'Access-Control-Allow-Credentials:' header

### ISSUE THREAD

**Issue by melvincarvalho** [linkeddata/gold#67]
Recently got an error of the kind:

    XMLHttpRequest cannot load https://databox.me/,proxy?uri=... A wildcard '*' 
    cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag
    is true.  Origin  is therefore not allowed access.

Running from localhost.

Response header

    Access-Control-Allow-Origin:*

I wonder if the proxy is getting blocked by CORS or if it's just a localhost issue.  I'll try and investigate further.  If anyone can reproduce, I'd be interested!

**Comment by dmitrizagidulin** [comment]
+1, ran into this also. The request is failing because, much [like ldnode](https://github.com/linkeddata/ldnode/issues/252), Gold's proxy is injecting an `Access-Control-Allow-Credentials: true` header.

Unlike, LDNode, Gold is also passing along the original server's `Access-Control-Allow-Origin: *` header, and the combination of those is not allowed by the browser.

**Comment by deiu** [comment]
Fixed in 6c754b10cdc0d9fc096442428cf101687983cdd5
